command_timeout = 500
[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[c]
symbol = "C "

[dotnet]
symbol = ".NET "

[directory]
read_only = " ro"

[docker_context]
symbol = "docker "

[git_branch]
symbol = "git "

[golang]
symbol = "go "

[java]
symbol = "java "

[kotlin]
symbol = "kt "

[lua]
symbol = "lua "

[nodejs]
symbol = "nodejs "

[memory_usage]
symbol = "memory "

[os.symbols]
Fedora = "fed "
Linux = "lnx "
Macos = "mac "
Raspbian = "rasp "
Ubuntu = "ubnt "

[package]
symbol = "pkg "

[php]
symbol = "php "

[python]
symbol = "py "

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[solidity]
symbol = "solidity "

[status]
symbol = "[x](bold red) "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "
